//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OtelRezervasyonPr
{
    using System;
    using System.Collections.Generic;
    
    public partial class OtelOzellik
    {
        public int OtelOzellikID { get; set; }
        public int OtelID { get; set; }
        public int OzellikID { get; set; }
        public bool OzellikDurum { get; set; }
    
        public virtual Otel Otel { get; set; }
        public virtual Ozellik Ozellik { get; set; }
    }
}
