//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OtelRezervasyonPr
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rezervasyon
    {
        public int RezervasyonID { get; set; }
        public int MusteriID { get; set; }
        public System.DateTime GirisTarihi { get; set; }
        public System.DateTime CikisTarihi { get; set; }
        public int OtelID { get; set; }
        public int OdaID { get; set; }
        public Nullable<System.DateTime> islemTarihi { get; set; }
    
        public virtual Musteri Musteri { get; set; }
        public virtual Oda Oda { get; set; }
        public virtual Otel Otel { get; set; }
    }
}
